<?php

/**
 * @file
 * USWDS Paragraphs module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uswds_paragraph_components_help($route_name, RouteMatchInterface $route_match): ?string {
  if ($route_name == 'help.page.uswds_paragraph_components') {
    $text = file_get_contents(dirname(__FILE__) . "/README.md");
    if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      // Use the Markdown filter to render the README.
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $settings = \Drupal::configFactory()
        ->get('markdown.settings')
        ->getRawData();
      $config = ['settings' => $settings];
      $filter = $filter_manager->createInstance('markdown', $config);
      return $filter->process($text, 'en');
    }
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function uswds_paragraph_components_theme($existing, $type, $theme, $path): array {
  return [
    'paragraph__default' => [
      'base hook' => 'paragraph',
    ],
  ];
}
