<?php

/**
 * @file
 * Support module for testing theme suggestions.
 */

/**
 * Implements hook_theme().
 */
function theme_suggestions_base3_test_theme($existing, $type, $theme, $path) {
  $items['theme_test_base3'] = [
    'variables' => [],
  ];
  return $items;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function theme_suggestions_base3_test_theme_suggestions_theme_test_base3_alter(array &$suggestions, array $variables, $hook) {
  $from_theme_array = array_search('theme_test_base3__from_theme_property', $suggestions);
  if ($from_theme_array !== FALSE) {
    $suggestions[$from_theme_array] .= '__seen_by_alter';
  }
  $suggestions[] = 'theme_test_base3__from_hook_theme_suggestions_hook_alter';
}
