<?php

/**
 * @file
 * USWDS Modal module file.
 */

/**
 * Implements hook_theme().
 */
function uswds_paragraph_components_modal_theme($existing, $type, $theme, $path): array {
  return [
    'paragraph__uswds_modal' => [
      'base hook' => 'paragraph',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 */
function uswds_paragraph_components_modal_preprocess_paragraph(&$variables) {
  $bundle = $variables['paragraph']->bundle();

  // Attach libraries for drupal integration
  // - preview view mode can be used in the admin theme by the
  // paragraphs form widget.
  if (substr($bundle, 0, 6) === 'uswds_' && $variables['view_mode'] !== 'preview') {
    $variables['#attached']['library'][] = 'uswds_paragraph_components_modal/uswds-modal';
  }
}
